accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/' , views.login_view, name='login'),
    path('logout/' , views.logout_view, name='logout'),
    path('profile/details/', views.profile_details, name='profile_details')
]

cinema_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticketing/' , include('ticketing.urls')),
    path('accounts/' , include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketing/urls.py
from django.urls import path

from ticketing import views

app_name = 'ticketing'
urlpatterns = [
    path('movie/list/', views.movie_list , name='movie_list'),
    path('cinema/list/', views.cinema_list , name='cinema_list'),
    path('movie/details/<int:movie_id>/', views.movie_details, name='movie_details'),
    path('cinema/details/<int:cinema_id>/', views.cinema_details, name='cinema_details'),
    path('showtime/list/', views.showtime_list, name='showtime_list'),
    path('ticket/list/', views.ticket_list, name='ticket_list'),
    path('ticket/details/<int:ticket_id>', views.ticket_details, name='ticket_details'),
    path('showtime/details/<int:showtime_id>/',views.showtime_details, name='showtime_details'),
]

ticketing/models.py
from django.db import models

class Movie(models.Model):

    class Meta:

        verbose_name = 'فیلم'
        verbose_name_plural = 'فیلم'


    name = models.CharField('نام فیلم' ,max_length=50)
    director = models.CharField('کارگردان' ,max_length=50)
    year = models.IntegerField('سال تولید')
    length = models.IntegerField('مدت زمان فیلم')
    desciption = models.TextField('توضیحات')
    poster = models.ImageField('پوستر', upload_to='movie_posters/' , blank=True)

    def __str__(self):
        return self.name

class Cinema(models.Model):

    class Meta:
        verbose_name = 'سینما'
        verbose_name_plural = 'سینما'
    name = models.CharField('نام' ,max_length=50)
    city = models.CharField('نام شهر' ,max_length=50 , default='تهران')
    capacity = models.IntegerField('ظرفیت')
    phone = models.CharField('تلفن' ,max_length=30 , null=True)
    address = models.TextField('آدرس')
    image = models.ImageField('تصویر', upload_to='cinema_images/' , null=True , blank=True)

    def __str__(self):
        return self.name


class ShowTime(models.Model):

    class Meta:

        verbose_name = 'سانس'
        verbose_name_plural = 'سانس'

    movie = models.ForeignKey('Movie' , on_delete=models.PROTECT ,verbose_name='فیلم')
    cinema = models.ForeignKey('Cinema' , on_delete=models.PROTECT ,verbose_name='سینما')

    start_time = models.DateTimeField('زمان شروع فیلم')
    price = models.IntegerField('قیمت')
    salable_seats = models.IntegerField('صندلی های قابل فروش')
    free_seats = models.IntegerField('صندلی های خالی')

    SALE_NOT_STARTED = 1
    SALE_OPENED = 2
    TICKETED_SOLD = 3
    SALE_CLOSED = 4
    MOVIE_PLAY = 5
    SHOW_CANCELED = 6
    status_choices = (
        (SALE_NOT_STARTED, 'فروش آغز نشده'),
        (SALE_OPENED, 'درحال فروش بلیت'),
        (TICKETED_SOLD, 'بلیت ها تمام شد'),
        (SALE_CLOSED, 'فروش بلیت تمام شد'),
        (MOVIE_PLAY, 'فیلم پخش شد'),
        (SHOW_CANCELED, 'سانس لغو شد')
    )
    status = models.IntegerField('وضعیت' ,choices=status_choices)

    def __str__(self):
        return '{} - {} - {}'.format(self.movie, self.cinema, self.start_time)


    def get_price_display(self):
        return '{}تومان'.format(self.price)

    def is_full(self):
        # return true if all seats sre sold #
        return self.free_seats == 0

    def open_sale(self):
        """
        opens ticket sale
        if sale was opened before, raise an exception
        """
        if self.status == ShowTime.SALE_NOT_STARTED:
            self.status = ShowTime.SALE_OPENED
            self.save()
        else:
            raise Exception('sale has been started before')

    def close_sale(self):
        """
        closes ticket sale
        if sale is mot open, raises an exception
        """
        if self.status == ShowTime.SALE_OPENED:
            self.status = ShowTime.SALE_CLOSED
            self.save()
        else:
            raise Exception('Sale is not open')

    def expire_showtime(self, is_canceled=False):
        """
        Expire showtime and updates the status
        :param is_canceled: A boolean indicating whether the show is canceled or not
        """
        if self.status not in (ShowTime.MOVIE_PLAY, ShowTime.SHOW_CANCELED):
            self.status = ShowTime.SHOW_CANCELED if is_canceled else ShowTime.MOVIE_PLAY
            self.save()
        else:
            raise  Exception('show has been expired before')

    def reserve_seats(self, seat_count):
        """
        Reseves one or more seats for a customer
        :param seat_count: An integer as the number of set ti be reserved
        """
        assert isinstance(seat_count, int) and seat_count>0 , 'Number of seat showtime is not integer'
        assert self.status == ShowTime.SALE_OPENED, 'sale is not open'
        assert self.free_seats >= seat_count, 'Not enough free seats'
        self.free_seats -= seat_count
        if self.free_seats == 0:
            self.status = ShowTime.TICKETED_SOLD
        self.save()

class Ticket(models.Model):
    """
    represents one or more tickets, bought by a user in an order
    """

    class Meta:
        verbose_name = 'بلیت'
        verbose_name_plural = 'بلیت'

    showtime = models.ForeignKey('ShowTime', on_delete=models.PROTECT, verbose_name='سانس')
    customer = models.ForeignKey('accounts.Profile', on_delete=models.PROTECT, verbose_name='خریدار')
    seat_count = models.IntegerField('تعداد صندلی')
    order_time = models.DateTimeField('زمان خرید', auto_now_add=True)

    def __str__(self):
        return '{}بلیت به نام{}برای فیلم{}'.format(self.seat_count, self.customer, self.showtime.movie)

ticketing/forms.py
from django import forms

from ticketing.models import Cinema


class ShowTimeSearchForm(forms.Form):
    movie_name = forms.CharField(max_length=100, label='نام فیلم' , required=False)
    sale_is_open = forms.BooleanField(label='فقط سانس های قابل خرید', required=False)
    movie_length_min = forms.IntegerField(label='حداقل زمان فیلم', min_value=0, max_value=200, required=False)
    movie_length_max = forms.IntegerField(label='حداکثر زمان فیلم', min_value=0, max_value=200, required=False)

    PRICE_ANY = '0'
    PRICE_UNDER_10 = '1'
    PRICE_10_TO_15 = '2'
    PRICE_15_TO_20 = '3'
    PRICE_ABOVE_20 = '4'
    PRICE_LEVEL_CHOICES = (

        (PRICE_ANY, 'هر قیمتی'),
        (PRICE_UNDER_10, 'تا 10 هزار تومان'),
        (PRICE_10_TO_15, '10 تا 15 هزار تومان'),
        (PRICE_15_TO_20, '15 تا 20 هزار تومان'),
        (PRICE_ABOVE_20, 'بیش از 20 هزار تومان'),
    )
    price_level = forms.ChoiceField(label='محدوده قیمت', choices=PRICE_LEVEL_CHOICES , required=False)

    cinema = forms.ModelChoiceField(label='سینما', queryset=Cinema.objects.all(), required=False)

    def get_price_boundries(self):
        price_level = self.cleaned_data['price_level']
        if price_level == ShowTimeSearchForm.PRICE_UNDER_10:
            return None,10000
        elif price_level == ShowTimeSearchForm.PRICE_10_TO_15:
            return 10000,15000
        elif price_level == ShowTimeSearchForm.PRICE_15_TO_20:
            return 15000,20000
        elif price_level == ShowTimeSearchForm.PRICE_ABOVE_20:
            return 20000,None
        else :
            return None,None

ticketing/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from ticketing.forms import ShowTimeSearchForm
from ticketing.models import Movie, Cinema, ShowTime, Ticket


def movie_list(request):
    movies = Movie.objects.all()
    count = len(movies)
    context = {
        'movie_list' : movies ,
        'movie_count' : count
    }
    return render(request, 'ticketing/movie_list.html', context)


def cinema_list(request):
    cinemas = Cinema.objects.all()
    context = {
        'cinema_list' : cinemas
    }
    return render(request , 'ticketing/cinema_list.html',context)


def movie_details(request , movie_id):
    movie = get_object_or_404(Movie , pk=movie_id)
    context = {
        'movie' : movie
    }
    return render(request,'ticketing/movie_details.html',context)


def cinema_details(request , cinema_id):
    cinema = get_object_or_404(Cinema , pk=cinema_id)
    context = {
        'cinema' : cinema

    }
    return render(request , 'ticketing/cinema_details.html' , context)


def showtime_list(request):
    search_form = ShowTimeSearchForm(request.GET)
    showtimes = ShowTime.objects.all()
    if search_form.is_valid():
        showtimes = showtimes.filter(movie__name__contains=search_form.cleaned_data['movie_name'])
        if search_form.cleaned_data['sale_is_open']:
            showtimes = showtimes.filter(status=ShowTime.SALE_OPENED)
        if search_form.cleaned_data['movie_length_min'] is not None:
            showtimes = showtimes.filter(movie__length__gte=search_form.cleaned_data['movie_length_min'])
        if search_form.cleaned_data['movie_length_max'] is not None:
            showtimes = showtimes.filter(movie__length__lte=search_form.cleaned_data['movie_length_max'])
        if search_form.cleaned_data['cinema'] is not None:
            showtimes = showtimes.filter(cinema = search_form.cleaned_data['cinema'])

        min_price, max_price = search_form.get_price_boundries()
        if min_price is not None:
            showtimes = showtimes.filter(price__gt=min_price)
        if max_price is not None:
            showtimes = showtimes.filter(price__lte=max_price)

    showtimes = showtimes.order_by('start_time')
    context = {
        'showtimes' : showtimes,
        'search_form' : search_form

    }
    return render(request, 'ticketing/showtime_list.html', context)

@login_required
def showtime_details(request, showtime_id):
    showtime = ShowTime.objects.get(pk=showtime_id)
    context = {
        'showtime' : showtime
    }
    # ---------------- (buy tickets) -------------------
    if request.method == 'POST':
        try:
            seat_count = int(request.POST['seat_count'])
            assert showtime.status == showtime.SALE_OPENED, 'فروش بلیت برای این سانس ممکن نیست'
            assert showtime.free_seats >= seat_count, 'ایت سانس صندلی خالی به اندازه کافی ندارد'
            total_price = showtime.price * seat_count
            assert request.user.profile.spend(total_price),'موجودی کافی نیست'
            showtime.reserve_seats(seat_count)
            ticket = Ticket.objects.create(showtime=showtime, customer=request.user.profile)
        except Exception as e:
            context['error'] = str(e)
        else:
            return HttpResponseRedirect(reverse('ticketing:ticket_details', kwargs={'ticket_id':ticket.id }))
    # --------------------------------------------------
    return render(request, 'ticketing/showtime_details.html', context)


@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(customer=request.user.profile).order_by('-order_time')
    context = {
        'tickets' : tickets
    }
    return render(request, 'ticketing/ticket_list.html', context)

@login_required
def ticket_details(request, ticket_id):
    ticket = Ticket.objects.get(pk=ticket_id)
    context = {
        'ticket' : ticket
    }
    return render(request, 'ticketing/ticket_details.html', context)

ticketing/templates/ticketing/_ad.html
<div class="alert alert-info col-11 mx-auto">
    تبلیغات شرکت ها اینجا قرار میگیرد.
</div>

ticketing/templates/ticketing/_base_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {% block extra_headers %}

    {% endblock %}
    {#    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/bootstrap.css" %}">#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css ">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/main.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/styles1001.css" %}">
    {% block extra_css %}


    {% endblock %}
</head>
<body dir="rtl">
<div class="main_page">
    <div class="header m-0">
        <div class="container">
            <div class="col text-center">
                <h2 class="header_title">
                    سامانه فروش بلیت سینما
                </h2>
            </div>
        </div>
    </div>
    <div class="toolbar row align-items-center m-0">
        <div class="container">
            <div class="row m-0">
                <div class="col-5">
                    <h4 class="section_title">
                        {% block toolbar_title %}

                        {% endblock %}
                    </h4>
                </div>
                <div class="col-7 text-left">
                    {% block toolbar_buttons %}
                        <div class="row m-0">
                            <a class="btn btn-light py-1 px-2 mx-1 mr-auto" href="{% url "ticketing:movie_list" %}">
                                <i class="fa fa-film"></i>
                                فیلم ها
                            </a>
                            <a class="btn btn-light py-1 px-2 mx-1" href="{% url "ticketing:cinema_list" %}">
                                <i class="fas fa-building"></i>
                                سینماها
                            </a>
                            <a class="btn btn-success py-1 px-2 mx-1" href="{% url "ticketing:showtime_list" %}">
                                <i class="fa fa-ticket-alt"></i>
                                خرید بلیت
                            </a>

                            {% if user.is_authenticated %}
                                <div class="dropdown">
                                    <a class="btn btn-primary dropdown-toggle py-1 px-2 mx-1" id="user-button" href="#"
                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        <i class="fas fa-user"></i>
                                        {{ user.get_full_name }}
                                    </a>
                                    <div class="dropdown-menu text-right" aria-labelledby="user-button">
                                        <div class="dropdown-item-text pr-4">
                                            <i class="fas fa-coins"></i>
                                            اعتبار:
                                            {{ user.profile.balance }}
                                            تومان
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url "accounts:profile_details" %}">
                                            <i class="far fa-address-card"></i>
                                            نمایه کاربری
                                        </a>
                                        <a class="dropdown-item" href="{% url "ticketing:ticket_list" %}">
                                            <i class="fas fa-ticket-alt"></i>
                                            بلیت های من
                                        </a>
                                        <a class="dropdown-item text-danger" href="{% url "accounts:logout" %}">
                                            <i class="fas fa-sign-out-alt"></i>
                                            خروج
                                        </a>
                                    </div>
                                </div>
                            {% else %}
                                <a class="btn btn-primary py-1 px-2 mr-3" href="{% url "accounts:login" %}">
                                    <i class="fas fa-sign-in-alt"></i>
                                    ورود
                                </a>
                            {% endif %}
                        </div>

                    {% endblock %}
                </div>
            </div>
        </div>

    </div>

    {% block main_content %}

    {% endblock %}

    <div class="footer">
        <div class="container text-center">
            <p class="footer_content">
                ما را در شبکه های اجتماعی دنبال کنید.
            </p>
            <a class="social-media-icon" href="https://facebook.com/#">
                <i class="fab fa-facebook social_icon"></i>
            </a>
            <a class="social-media-icon" href="https://twitter.com/#">
                <i class="fab fa-twitter social_icon"></i>
            </a>
            <a class="social-media-icon" href="https://instagram.com/#">
                <i class="fab fa-instagram social_icon"></i>
            </a>
            <a class="social-media-icon" href="https://telegram.com/#">
                <i class="fab fa-telegram social_icon"></i>
            </a>
        </div>
    </div>
</div>
{#<script src="{% static "ticketing/js/jquery-3.5.0.min.js" %}"></script>#}
{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>#}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
{#<script src="{% static "ticketing/js/bootstrap.bundle.js" %}"></script>#}
{#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<script src="{% static "ticketing/js/main.js" %}"></script>
</body>
</html>

ticketing/templates/ticketing/_form_field.html
<div class="show_time_inputs col-12">
    <div class="">
    <div class="row m-0">
        <label class="col-{{ label_size|default:2 }} show_time_label mr-auto" for="{{ field.id_for_label }}">
            {{ field.label }}
        </label>
        <div class="col-{{ input_size|default:4 }} show_time_input ml-auto">
            {{ field }}
            {{ field.errors }}
        </div>
    </div>
</div>
</div>

ticketing/templates/ticketing/cinema_list.html
{% extends "ticketing/_base_page.html" %}


{% block title %}
فهرست سینماها
{% endblock %}


{% block toolbar_title %}
فهرست سینماها
{% endblock %}


{% block main_content %}
<div class="movie_list_section">
    <div class="container py-3">
        {% if cinema_list %}
            <ul class="item-list movie_lists">
                {% for cinema in cinema_list%}
                    <li class="col-11 mx-auto my-1 movie_item">
                    <a href="{% url "ticketing:cinema_details" cinema_id=cinema.id %}" class="movie_link">
                        <i class="fa fa-film"></i>
                        <span class="movie_name">
                            {{ cinema }}
                        </span>
                        <small class="director">
                            ({{ cinema.city }})
                        </small>
                    </a>
                    </li>
                {% endfor %}

            </ul>
        {% else %}
            <div class="alert alert-danger col-11 mx-auto">
                متاسفانه هیچ سینمایی یافت نشد.
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

ticketing/templates/ticketing/showtime_details.html
{% extends "ticketing/_base_page.html" %}
{% load static %}

{% block title %}
    خرید بلیت
{% endblock %}

{% block toolbar_title %}
<i class="fas fa-play-circle"></i>
    {{ showtime.movie }}
    <small class="showtime">
        ({{ showtime.start_time }})
    </small>
{% endblock %}

{% block toolbar_buttons %}
    <a class="btn btn-warning py-1 px-2" href="{% url "ticketing:showtime_list" %}">
        <i class="fas fa-list"></i>
        فهرست سانس ها
    </a>
    <div class="dropdown">
        <a class="btn btn-primary dropdown-toggle py-1 px-2" id="user-button" href="#"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <i class="fas fa-user"></i>
            {{ user.get_full_name }}
        </a>
        <div class="dropdown-menu text-right" aria-labelledby="user-button">
            <span class="dropdown-item-text">
                <i class="fas fa-coins"></i>
                اعتبار:
                {{ user.profile.balance }}
                تومان
            </span>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url "accounts:profile_details" %}">
                <i class="far fa-address-card"></i>
                نمایه کاربری
            </a>
            <a class="dropdown-item" href="{% url "ticketing:ticket_list" %}">
                <i class="fas fa-ticket-alt"></i>
                بلیت های من
            </a>
            <a class="dropdown-item" href="{% url "accounts:logout" %}">
                <i class="fas fa-sign-out-alt"></i>
                خروج
            </a>
        </div>
    </div>
{% endblock %}


{% block main_content %}
<div class="row py-3">
        <div class="col-8 item-details">
            <div class="row px-3">
                {% if showtime.status == showtime.SALE_OPENED %}
                    <div class="col-4">
                        <small class="text-muted">
                            <i class="fa fa-film"></i>
                            نام فیلم:
                        </small>
                    </div>
                    <div class="col-8">
                        {{ showtime.movie }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-4">
                        <small class="text-muted">
                            <i class="fas fa-building"></i>
                            نام سینما:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ showtime.cinema}}
                    </div>
                    <div class="col-4 text-left">
                        <a class="btn btn-xs btn-primary my-1">
                            {{ showtime.free_seats }}
                            صندلی مانده
                        </a>
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-4">
                        <small class="text-muted">
                            <i class="fas fa-clock"></i>
                            شروع سانس:
                        </small>
                    </div>
                    <div class="col-8">
                        {{  showtime.start_time|date:"l Y/n/j ساعت H:i"  }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="fas fa-location-arrow"></i>
                            آدرس سینما:
                        </small>
                    </div>
                    <div class="col-10 item-text-box">
                        {{ showtime.cinema.address }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-3">
                        <small class="text-muted">
                            <i class="fas fa-money-bill-wave"></i>
                            قیمت بلیت:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ showtime.price }}
                        تومان
                    </div>
                    <div class="col-5">
                    <form action="" method="post" class="form-inline">
                        {% csrf_token %}
                        <select name="seat_count" class="form-control form-control-sm ml-2">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <button type="submit" class="btn btn-xs btn-success my-1" href="#">
                            خرید بلیت
                        </button>
                    </form>
                    </div>
                {% endif %}
                {% if error %}
                    <div class="w-100 my-1"></div>
                    <span class="col-12 alert-danger align-items-baseline small">
                        <i class="fas fa-exclamation-circle"></i>
                        {{ error }}
                    </span>
                {% endif %}
            </div>
        </div>
        <div class="col-4 text-center" >
            <img class="item-image" src="{{ showtime.movie.poster.url }}" alt="{{ cinema.name }}">
            <i class="far fa-10x fa-building text-muted"></i>
        </div>
    </div>
{% endblock %}

ticketing/templates/ticketing/showtime_list.html
{% extends "ticketing/_base_page.html" %}
{% load static %}
{% block title %}
    سانس های نمایش فیلم
{% endblock %}

{% block toolbar_title %}
    فهرست سانس های نمایش
{% endblock %}

{% block main_content %}
    <div class="show_time_list">
        <div class="container">
            <div class="row m-0">
                <div class="col py-3">
                    <div class="row">
                        <div class="col my-1 mx-3 py-2 px-3 search-bar">
                            <form action="" method="get" class="form-row px-2">
                                {% include "ticketing/_form_field.html" with field=search_form.movie_name %}
                                {% include "ticketing/_form_field.html" with field=search_form.cinema %}

                                {% include "ticketing/_form_field.html" with field=search_form.movie_length_min label_size=2 input_size=4 %}
                                {% include "ticketing/_form_field.html" with field=search_form.movie_length_max label_size=2 input_size=4 %}

                                {% include "ticketing/_form_field.html" with field=search_form.price_level  %}
                                <div class="col-12" >
                                    <div class="col-6 mx-auto">
                                    {{ search_form.sale_is_open }}
                                    {{ search_form.sale_is_open.label }}
                                </div>
                                </div>

                                <button type="submit" class="btn btn-primary btn-sm mx-auto">
                                    جستجو
                                </button>
                            </form>
                        </div>
                    </div>
                    {% if showtimes %}
                        <div class="row px-2">
                            <div class="col">
                                <div class="alert alert-info mt-2 mb-0 py-1 px-3">
                                    {{ showtimes.count }}
                                    سانس یافت شد.
                                </div>
                            </div>
                        </div>
                        <div class="row px-2">
                            {% for showtime in showtimes %}
                                <div class="col-3 px-2 py-2">
                                    <a href="{% url "ticketing:showtime_details" showtime_id=showtime.id %}"
                                       class="showtime-box btn
                                {% if showtime.status != showtime.SALE_OPENED %}
                                    disabled btn-outline-secondary
                                {% else %}
                                    btn-outline-dark
                                {% endif %}
                                ">
                                        <span>{{ showtime.movie }}</span>
                                        <br/>
                                        <span>{{ showtime.cinema }}</span>
                                        <br/>
                                        <span>
                                {{ showtime.start_time|date:"l Y/n/j ساعت H:i" }}
                            </span>

                                        <span class="showtime-status badge
                                {% if showtime.status == showtime.SALE_NOT_STARTED %}
                                    badge-warning
                                {% elif showtime.status == showtime.SHOW_CANCELED %}
                                    badge-danger
                                {% elif showtime.status == showtime.SALE_OPENED %}
                                    badge-success
                                {% else %}
                                    badge-secondary
                                {% endif %}">
                                {% if showtime.status == showtime.SALE_OPENED %}
                                    {{ showtime.get_price_display }}
                                {% else %}
                                    {{ showtime.get_status_display }}
                                {% endif %}
                            </span>
                                        {% if showtime.status == showtime.SALE_OPENED and showtime.free_seats < 10 %}
                                            <span class="badge badge-danger">
                                {{ showtime.free_seats }}
                                صندلی
                                </span>
                                        {% endif %}
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="alert alert-danger">
                            در حال حاضر هیچ سانسی برای نمایش فیلم وجود ندارد.
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}